name: 'neo-cowsay'
description: 'Wraps some messages by neo-cowsay'
branding:
  icon: 'bell'
  color: 'gray-dark'
inputs:
  message:
    description: 'What you want to say'
    required: true
  cow:
    description: 'Choose the cow you want to say'
    default: 'default'
  cowsay_on_comment:
    description: 'Whether or not to comment on pull requests'
  cowsay_to_output:
    description: 'Set cowsay to you specified output'
runs:
  using: 'docker'
  image: 'Dockerfile'
