name: 'cowsay'
description: 'Wraps some messages by cowsay'
inputs:
  message:
    description: 'What you want to say'
    required: true
  cow:
    description: 'Choose the cow you want to say'
    default: 'default'
  cowsay_on_comment:
    description: 'Whether or not to comment on pull requests.'
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
