on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: A test job to cowsay
    steps:
    - name: Test just output the message
      uses: actions/checkout@v1
      with:
        message: >
          This is cowsay
          Hello, World!!
    - name: Test cowsay on the comment
      uses: actions/checkout@v1
      with:
        message: 'Hello, World with docker'
        cow: 'docker'
        cowsay_on_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test set output pipeline
      id: cowsay_output_id
      uses: actions/checkout@v1
      with:
        message: 'Hello, World'
        cow: 'gopher'
        cowsay_to_output: 'cowsay'
    - name: Print output
      run: |
        echo "${{ steps.cowsay_output_id.outputs.cowsay }}"
    
